---
title: "NBA Prediction Regression"
author: "STAT 471/571/701 Modern Data Mining"
date: "12/??/2018"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 4)
if(!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, glmnet, car)
```

```{r data preparation, include=F}
data <- read.csv("terrorism.csv")
```

```{r, include=F}
data_2017 <- data %>% filter(iyear == 2017)
```

```{r, include = F}
data_2017_filtered <- data_2017 %>% select(-c(approxdate, resolution, location, summary, alternative, alternative_txt, attacktype2, attacktype2_txt, attacktype3, attacktype3_txt, targtype2, targtype2_txt, targsubtype2, targsubtype2_txt, corp2, target2, natlty2, natlty2_txt, targtype3, targtype3_txt, targsubtype3, targsubtype3_txt, corp3, target3, natlty3, natlty3_txt, gsubname, gname2, gsubname2, gname3, gsubname3, motive, guncertain2, guncertain3, claim2, claimmode2, claimmode2_txt, claim3, claimmode3, claimmode3_txt, compclaim, weaptype1, weapsubtype1, weaptype2, weaptype2_txt, weapsubtype2, weapsubtype2_txt, weaptype3, weaptype3_txt, weapsubtype3, weapsubtype3_txt, weaptype4, weaptype4_txt, weapsubtype4, weapsubtype4_txt, nhostkid, nhostkidus, nhours, ndays, divert, kidhijcountry, ransom, ransomamt, ransomamtus, ransompaid, ransompaidus, ransomnote, hostkidoutcome, hostkidoutcome_txt, nreleased, addnotes, scite1, scite2, scite3, dbsource, INT_LOG, INT_IDEO, INT_MISC, INT_ANY, related))

# remove text or IDs
data_2017_filtered <- data_2017_filtered %>% select(-c(country, region, attacktype1, targtype1, targsubtype1, natlty1, claimmode, propextent, propcomment))
```

```{r, include = F}
# Ransom!
#data_ransom <- data %>% filter(ransom == 1)
#data_multiple_2 <- data %>% filter(gname3 != "")
#data_multiple_3 <- data %>% filter(gname3 != "")
#data_usa <- data %>% filter(country == 217)
#data_iraq <- data %>% filter(country == 92)
#data_syria <- data %>% filter(country == 200)
#data_developed <- data %>% filter(region == 1 | region == 8 | region == 4)
#data_japan <- data %>% filter(country == 101)
#data_police <- data %>% filter(targtype1_txt == 'Police')
#data_military <- data %>% filter(targtype1_txt == 'Military')
#data_government <- data %>% filter(targtype1 == 2 | targtype1 == 7)
summary(data$nkill)
summary(data$nwound)

# Notes: should we filter out nkill - nwound, propcomment stuff? predict on these?
```